import { computed } from 'vue'
import schemaData from '../schema.json'
import { config, getShareableUrl } from './config'

// --- Types ---

export interface SchemaOption {
  value: string
  label: string
  description?: string
}

export interface Condition {
  field?: string
  eq?: any
  neq?: any
  notEmpty?: boolean
  startsWith?: string
  or?: Condition[]
  and?: Condition[]
}

export type ConditionOrString = string | Condition

export interface EnvRule {
  key: string
  format?: 'boolToFlag' | 'raw'
  omitDefault?: boolean
  always?: boolean
  static?: string
  when?: ConditionOrString
}

export interface YamlRule {
  file: string
  path: string
  when?: ConditionOrString
  value?: any
}

export interface InfraMatchEntry {
  when?: Condition
  value?: string
  default?: string
}

export interface InfraRule {
  id: string
  label: string | { match: InfraMatchEntry[] }
  icon: string
  color: string
  category: string
  connectionLabel: string
  dashed?: boolean
  when?: ConditionOrString
}

export interface Field {
  key: string
  type: 'text' | 'number' | 'select' | 'toggle' | 'textarea' | 'checklist' | 'tags' | 'domain-rewrites' | 'hidden'
  label: string
  default: any
  description?: string
  hint?: string
  placeholder?: string
  showWhen?: string
  options?: SchemaOption[]
  min?: number
  env?: EnvRule
  yaml?: YamlRule | YamlRule[]
  infra?: InfraRule
}

export interface Group {
  title: string
  showWhen?: string
  fields: Field[]
}

export interface Section {
  id: string
  title: string
  description: string
  icon: string
  category: string
  groups: Group[]
}

export interface Schema {
  sections: Section[]
}

// --- Schema access ---

export const schema: Schema = schemaData as Schema

// --- Defaults ---

export function extractDefaults(): Record<string, any> {
  const defaults: Record<string, any> = {}
  for (const section of schema.sections) {
    for (const group of section.groups) {
      for (const field of group.fields) {
        if (!field.key.startsWith('_')) {
          defaults[field.key] = field.default
        }
      }
    }
  }
  return defaults
}

// --- Condition evaluator ---

function normalizeCondition(c: ConditionOrString): Condition {
  if (typeof c === 'string') {
    return { field: c, eq: true }
  }
  return c
}

export function evaluateCondition(condition: ConditionOrString | undefined, state: Record<string, any>): boolean {
  if (condition === undefined) return true

  const c = normalizeCondition(condition)

  if (c.or) {
    return c.or.some(sub => evaluateCondition(sub, state))
  }
  if (c.and) {
    return c.and.every(sub => evaluateCondition(sub, state))
  }

  if (!c.field) return true
  const val = state[c.field]

  if (c.notEmpty !== undefined) {
    if (typeof val === 'string') return val.length > 0
    if (Array.isArray(val)) return val.length > 0
    return !!val
  }
  if (c.startsWith !== undefined) {
    return typeof val === 'string' && val.startsWith(c.startsWith)
  }
  if (c.neq !== undefined) {
    return val !== c.neq
  }
  if (c.eq !== undefined) {
    return val === c.eq
  }

  // Default: truthy check
  return !!val
}

// --- All fields iterator ---

function allFields(): Field[] {
  const fields: Field[] = []
  for (const section of schema.sections) {
    for (const group of section.groups) {
      for (const field of group.fields) {
        fields.push(field)
      }
    }
  }
  return fields
}

// --- Field to section mapping (for env comments) ---

function fieldSectionMap(): Map<string, string> {
  const map = new Map<string, string>()
  for (const section of schema.sections) {
    for (const group of section.groups) {
      for (const field of group.fields) {
        map.set(field.key, section.title)
      }
    }
  }
  return map
}

// --- Env generator ---

function formatEnvValue(value: any, format?: string): string {
  if (format === 'boolToFlag') {
    return value ? '1' : '0'
  }
  return String(value)
}

export const generatedEnv = computed(() => {
  const state = config as unknown as Record<string, any>
  const lines: string[] = []
  const sectionMap = fieldSectionMap()
  let lastSection = ''

  lines.push('# Shopware Environment Configuration')
  lines.push('# Generated by Shopware Config Generator')
  lines.push(`# ${getShareableUrl()}`)
  lines.push('')

  for (const field of allFields()) {
    if (!field.env) continue

    const env = field.env
    const value = state[field.key]
    const defaultVal = field.default

    // Evaluate conditions: env.when takes priority, then showWhen
    if (env.when) {
      if (!evaluateCondition(env.when, state)) continue
    } else if (field.showWhen) {
      if (!evaluateCondition(field.showWhen, state)) continue
    }

    // omitDefault check
    if (env.omitDefault && JSON.stringify(value) === JSON.stringify(defaultVal)) continue

    // Determine the actual output value
    let outputValue: string
    if (env.static !== undefined) {
      outputValue = env.static
    } else {
      outputValue = formatEnvValue(value, env.format)
    }

    // For static env values, only output when the field value is truthy
    if (env.static !== undefined && !value) continue

    // Skip empty values unless always
    if (!env.always) {
      if (env.format === 'boolToFlag' && value === false) continue
      if (outputValue === '') continue
    }

    // Section comment
    const section = sectionMap.get(field.key) || ''
    if (section !== lastSection) {
      if (lastSection !== '') lines.push('')
      lines.push(`# ${section}`)
      lastSection = section
    }

    lines.push(`${env.key}=${outputValue}`)
  }

  return lines.join('\n')
})

// --- YAML generator ---

function setNestedValue(obj: Record<string, any>, path: string, value: any): void {
  const parts = path.split('.')
  let current = obj
  for (let i = 0; i < parts.length - 1; i++) {
    const part = parts[i]!
    if (!(part in current)) {
      current[part] = {}
    }
    current = current[part]
  }
  current[parts[parts.length - 1]!] = value
}

function serializeYaml(obj: Record<string, any>, indent: number = 0): string {
  const lines: string[] = []
  const prefix = '    '.repeat(indent)

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) {
      lines.push(`${prefix}${key}: null`)
    } else if (Array.isArray(value)) {
      if (value.length === 0) {
        lines.push(`${prefix}${key}: []`)
      } else {
        lines.push(`${prefix}${key}:`)
        for (const item of value) {
          if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
            // Object array items (like domain rewrites)
            const entries = Object.entries(item)
            if (entries.length > 0) {
              const [firstKey, firstVal] = entries[0]!
              lines.push(`${prefix}    - ${firstKey}: ${formatYamlValue(firstVal)}`)
              for (let i = 1; i < entries.length; i++) {
                const [k, v] = entries[i]!
                lines.push(`${prefix}      ${k}: ${formatYamlValue(v)}`)
              }
            }
          } else {
            lines.push(`${prefix}    - ${formatYamlValue(item)}`)
          }
        }
      }
    } else if (typeof value === 'object') {
      lines.push(`${prefix}${key}:`)
      lines.push(serializeYaml(value, indent + 1))
    } else {
      lines.push(`${prefix}${key}: ${formatYamlValue(value)}`)
    }
  }

  return lines.join('\n')
}

function formatYamlValue(value: any): string {
  if (typeof value === 'boolean') return value.toString()
  if (typeof value === 'number') return value.toString()
  if (typeof value === 'string') {
    if (value === '') return 'null'
    if (value === 'null') return 'null'
    // Quote strings that contain special characters or look like other types
    if (value.startsWith('%') || value.includes('"') || value.includes("'") || value.includes(':') || value.includes('#')) {
      return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
    }
    if (/^\d+$/.test(value)) {
      return `'${value}'`
    }
    return value
  }
  return String(value)
}

interface YamlFileOutput {
  file: string
  label: string
  content: string
}

export const generatedYamlFiles = computed<YamlFileOutput[]>(() => {
  const state = config as unknown as Record<string, any>
  const fileData: Record<string, Record<string, any>> = {}

  for (const field of allFields()) {
    if (!field.yaml) continue

    const rules = Array.isArray(field.yaml) ? field.yaml : [field.yaml]

    for (const rule of rules) {
      // Evaluate condition
      if (rule.when !== undefined) {
        if (!evaluateCondition(rule.when, state)) continue
      }

      // Get value
      const value = rule.value !== undefined ? rule.value : state[field.key]

      // Skip undefined/null
      if (value === undefined || value === null) continue

      // Initialize file object
      if (!fileData[rule.file]) {
        fileData[rule.file] = {}
      }

      setNestedValue(fileData[rule.file]!, rule.path, value)
    }
  }

  const result: YamlFileOutput[] = []

  for (const [file, data] of Object.entries(fileData)) {
    if (Object.keys(data).length === 0) continue

    const comment = `# config/packages/${file.includes('monolog') ? 'prod/' : ''}${file}`
    const urlComment = `# ${getShareableUrl()}`
    const yamlContent = serializeYaml(data)
    result.push({
      file,
      label: file,
      content: `${comment}\n${urlComment}\n${yamlContent}`,
    })
  }

  return result
})

// --- Infrastructure nodes ---

export interface InfraNode {
  id: string
  label: string
  icon: string
  color: string
  category: string
  connectionLabel: string
  dashed?: boolean
}

export const infraNodes = computed<InfraNode[]>(() => {
  const state = config as unknown as Record<string, any>
  const seen = new Set<string>()
  const nodes: InfraNode[] = []

  for (const field of allFields()) {
    if (!field.infra) continue

    const infra = field.infra
    if (seen.has(infra.id)) continue

    // Evaluate when condition
    if (infra.when) {
      if (!evaluateCondition(infra.when, state)) continue
    } else {
      // Default: field value is truthy
      if (!state[field.key]) continue
    }

    seen.add(infra.id)

    // Resolve dynamic label
    let label: string
    if (typeof infra.label === 'string') {
      label = infra.label
    } else {
      label = resolveMatchLabel(infra.label.match, state)
    }

    nodes.push({
      id: infra.id,
      label,
      icon: infra.icon,
      color: infra.color,
      category: infra.category,
      connectionLabel: infra.connectionLabel,
      dashed: infra.dashed,
    })
  }

  return nodes
})

function resolveMatchLabel(matches: InfraMatchEntry[], state: Record<string, any>): string {
  for (const entry of matches) {
    if (entry.default) return entry.default
    if (entry.when && evaluateCondition(entry.when, state) && entry.value) {
      return entry.value
    }
  }
  return ''
}
